export default {
  openSansBold: 'OpenSans-Bold',
  openSansBoldItalic: 'OpenSans-BoldItalic',
  openSansExtraBold: 'OpenSans-ExtraBold',
  openSansExtraBoldItalic: 'OpenSans-ExtraBoldItalic',
  openSansItalic: 'OpenSans-Italic',
  openSansLight: 'OpenSans-Light',
  openSansLightItalic: 'OpenSans-LightItalic',
  openSansMedium: 'OpenSans-Medium',
  openSansMediumItalic: 'OpenSans-MediumItalic',
  openSansRegular: 'OpenSans-Regular',
  openSansSemiBold: 'OpenSans-SemiBold',
  openSansSemiBoldItalic: 'OpenSans-SemiBoldItalic',
  neonDerthawRegular: 'Neonderthaw-Regular',
};
